name: simple_retrieval_augmented_generation_env
channels:
  - conda-forge
  - pytorch
  - moustik
dependencies:
  - python=3.8
  - mkl
  - faiss-cpu=1.7.4
  - pandas
  - nltk
  - numpy
  - transformers
  - pytorch
  - scikit-learn
  - langchain
  - langchain-openai
  - langsmith
  - streamlit
  - langdetect
  - pyyaml
  - packaging
  - faker
  - spacy
  - langdetect
  - fasttext
  - httpx=0.27.0
  - contractions
  - requests

